Upgrade to latest version of gradle plugin
VEuPathDB/EdaUserService pull request #16
Opened 2022-12-09 16:48 UTC by dmgaldi

## Overview
* Upgrade user service to use gradle plugin for RAML generation
* Upgrade container core version to the latest

Note: we could probably delete the makefile if we want to? I left it for now for compatibility but let me know if you want me to delete it.

## Testing
* Ran gradle tasks successfully

2022-12-13 14:43 UTC, dmgaldi commented
> I'm not actually sure I like this way better. Harder to track what all is going on. Like if I run make gen-jaxrs, I can track each step along the way. But by tacking on pre- and post-conditions to a "well known" gradle target, it could be a total mystery how it happens to someone not in the know.

Do you think we should have a gradle plugin task for fetching the RAML? I was hesitant since it's only done in EDA at the moment. I'm not sure how one would "opt into", "opt out of" or configure the common RAML fetch task if we put it in the plugin.

2022-12-13 18:03 UTC, dmgaldi commented
> > I'm not actually sure I like this way better. Harder to track what all is going on. Like if I run make gen-jaxrs, I can track each step along the way. But by tacking on pre- and post-conditions to a "well known" gradle target, it could be a total mystery how it happens to someone not in the know.
> 
> Do you think we should have a gradle plugin task for fetching the RAML? I was hesitant since it's only done in EDA at the moment. I'm not sure how one would "opt into", "opt out of" or configure the common RAML fetch task if we put it in the plugin.

Talked about this after scrum, updated based on our conversation and Ellie's help

2023-01-06 15:03 UTC, ryanrdoherty commented
@dmgaldi @Foxcapades Can you take a look at this as a final cut?  I think it's ready to merge; can maybe be a template to improve all the other services (esp EDA services).

2023-01-06 15:09 UTC, ryanrdoherty commented
@steve-fischer-200 Please review the Java code

2023-01-09 14:29 UTC, steve-fischer-200 commented on src/main/java/org/veupathdb/service/eda/us/model/UserDataFactory.java
> +   *** Exception handling so underlying message is not exposed to user
These methods should be in FgpUtil

2023-01-09 15:20 UTC, steve-fischer-200 commented on src/main/java/org/veupathdb/service/eda/us/model/UserDataFactory.java
> +    Throwable root = e instanceof SQLRunnerException ? e.getCause() : e;
i don't fully understand why getCause() is what we want here

2023-01-09 15:30 UTC, steve-fischer-200 requested changes
looks good.  i requested changes cuz of my suggestion about moving methods to fgputil

2023-01-12 11:23 UTC, merged